# Supabase Local Development Configuration

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[analytics]
enabled = false

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083